---
- name: Create common (empty) files / directories
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: '{{ item.owner|default(omit) }}'
    group: '{{ item.group|default(omit) }}'
    state: '{{ item.state|default(omit) }}'
  loop: "{{ bootstrap_directories|default([]) }}"
  loop_control:
    label: "{{ item.path }}"

- name: Copy common files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    force: '{{ item.force|default(omit) }}'
  loop: "{{ bootstrap_files|default([]) }}"
  loop_control:
    label: "{{ item.dest }}"

- name: Apply / deploy common templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode|default(omit) }}"
  loop: "{{ bootstrap_templates|default([]) }}"
  loop_control:
    label: "{{ item.dest }}"
  tags:
    - templates
