---
- name: Create common (empty) files / directories
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: '{{ item.owner|default("root") }}'
    group: '{{ item.group|default("root") }}'
    state: '{{ item.state|default("directory") }}'
  loop: "{{ bootstrap_directories|default([]) }}"

- name: Copy common files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    force: '{{ item.force|default("yes") }}'
  loop: "{{ bootstrap_files|default([]) }}"
