---
# tasks file for bootstrap
- include_tasks: packages.yml
  tags: packages

# Weirdly enough this sometimes necessitates a reboot
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - hostname

- name: Find out kernel version
  ansible.builtin.command: uname -r
  register: kernel_running
  changed_when: false
  tags:
    - experimental

- name: Check if the most recent kernel is running
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo $(readlink -f /vmlinuz) | sed -e "s/\/boot\/vmlinuz-//"
    executable: /bin/bash
  register: kernel_booting
  changed_when: false
  tags:
    - experimental

- name: Check if github.com can be resolved
  command: getent hosts github.com
  register: resolved
  ignore_errors: yes
  changed_when: resolved.rc
  tags:
    - experimental

- name: Reboot if required
  reboot:
  when: bootstrap_reboot_allowed and ((kernel_running.stdout != kernel_booting.stdout) or resolved.rc != 0)
  tags:
    - experimental

- include_tasks: users.yml
  tags: users

- name: Set locale (needs locale package)
  locale_gen:
    name: "{{ bootstrap_locale|default('en_US.UTF-8') }}"
    state: present
  ignore_errors: yes

- name: Install common git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    depth: "{{ item.depth|default('1') }}"
    accept_hostkey: yes
    version: "{{ item.version|default('master') }}"
    force: "{{ item.force|default('no') }}"
  loop: "{{ bootstrap_git_repositories|default([]) }}"
  loop_control:
    label: "{{ item.repo }}"
  # local modifications allowed
  failed_when: false

- import_tasks: files.yml

- name: Allow ssh through firewall
  ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  notify:
    - Reload ufw
  tags:
    - ssh
  with_items: "{{ bootstrap_ufw_tcp_allow }}"
  when: bootstrap_ufw_tcp_allow|length

- name: Make sure firewall is up and running, and denying
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  notify:
    - Reload ufw
  tags:
    - ssh
  when: bootstrap_ufw_tcp_allow|length

- name: Remove insufficient moduli settings
  lineinfile: dest=/etc/ssh/moduli
    regexp=" {{ item }} "
    line="{{ item }}"
    state=absent
  with_items: "{{ sshd_moduli_remove|default([]) }}"
  notify:
    - Restart sshd
  tags:
    - ssh

- name: Disable grub timeout
  lineinfile: dest=/etc/default/grub
    regexp="^{{ item.name }}="
    line="{{ item.name }}={{ item.value }}"
    state=present
  with_items: "{{ grub_settings|default([]) }}"
  notify: Reload grub config
  tags:
    - grub

- include_tasks: timezone.yml
  tags: timezone

- include_tasks: mounts.yml
  tags: mounts

- name: Run post-provision commands
  command: "{{ item }}"
  loop: "{{ bootstrap_commands|default([]) }}"
  changed_when: false
  tags:
    - commands
