---
- name: Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ bootstrap_packages_remove|default([]) }}"
    force: true
    autoclean: true
    autoremove: true
    state: absent

- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 86400
  tags:
    - update

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ bootstrap_packages|default([]) }}"
    update_cache: true
    install-recommends: true
    state: present

- name: Install common pip packages
  ansible.builtin.pip:
    name: "{{ bootstrap_pip_packages|default([]) }}"
    executable: "{{ bootstrap_pip_version|default('pip3') }}"
    state: present
  when:
    - bootstrap_pip_packages|default([])|length

- name: Install third-party packages
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop: "{{ bootstrap_url_packages|default([]) }}"

- name: Update alternatives
  alternatives:
    link: "{{ item.link }}"
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  loop: "{{ bootstrap_alternatives|default([]) }}"
