---
- name: Add standard groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid|default(omit) }}"
    system: "{{ item.system|default(omit) }}"
  loop: "{{ bootstrap_groups|default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Remove groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: absent
  loop: "{{ bootstrap_groups_remove|default([]) }}"

- name: Add users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    shell: "{{ item.shell|default(omit) }}"
    password: "{{ item.password|default(omit) }}"
    groups: "{{ ','.join(item.groups|default([])) }}"
    state: present
    update_password: on_create
    create_home: "{{ item.create_home|default(omit) }}"
    home: "{{ item.home|default(omit) }}"
    system: "{{ item.system|default(omit) }}"
    generate_ssh_key: "{{ item.generate_ssh_key|default(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits|default(4096) }}"
    ssh_key_comment: "{{ item.ssh_key_comment|default('') }}"
  loop: "{{ bootstrap_users|default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Allow passwordless sudo for sudo users
  ansible.builtin.template:
    src: sudo.j2
    dest: "/etc/sudoers.d/{{ item.name }}"
    mode: "0440"
  loop: "{{ bootstrap_users|default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.groups is defined and 'sudo' in item.groups

- name: Add public SSH keys per user
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    validate_certs: "{{ item.validate_certs|default(omit) }}"
  loop: "{{ bootstrap_users|default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.ssh_key is defined

- name: Install git repos per user
  ansible.builtin.git:
    repo: "{{ item[1].src }}"
    dest: "{{ item[1].dest }}"
    depth: 1
    accept_hostkey: true
    version: "{{ item[1].version|default(omit) }}"
  become_user: "{{ item[0].name }}"
  become: true
  loop: "{{ lookup('subelements', bootstrap_users, 'repos', {'skip_missing': True}, wantlist=True) }}"
  loop_control:
    label: "{{ item[1].src }}"

- name: Set correct ownership for personal git repos
  ansible.builtin.file:
    name: "{{ item[1].dest }}"
    owner: "{{ item[0].name }}"
    group: "{{ item[0].name }}"
    recurse: true
  loop: "{{ lookup('subelements', bootstrap_users, 'repos', {'skip_missing': True}, wantlist=True) }}"
  loop_control:
    label: "{{ item[1].dest }}"

- name: Execute installers for users
  ansible.builtin.command: "{{ item[1].command }}"
  become: true
  become_user: "{{ item[0].name }}"
  register: result
  loop: "{{ lookup('subelements', bootstrap_users, 'installers', {'skip_missing': True}, wantlist=True) }}"
  loop_control:
    label: "{{ item[1].command }}"
  changed_when: result.rc != 0
