---
- name: Add standard groups
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ bootstrap_groups|default([]) }}"

- name: Remove groups
  group:
    name: "{{ item }}"
    state: absent
  with_items: "{{ bootstrap_groups_remove|default([]) }}"

- name: Add users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    password: "{{ item.password|default([]) }}"
    groups: "{{ ','.join(item.groups) }}"
    state: present
    update_password: on_create
  loop: "{{ bootstrap_users|default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Allow passwordless sudo for sudo users
  lineinfile: "dest=/etc/sudoers
    state=present
    regexp='^{{ item }}'
    insertafter=EOF
    line='{{ item }} ALL=(ALL) NOPASSWD: ALL'"
  loop: "{{ bootstrap_sudo_users|default([]) }}"

- name: Add public SSH keys per user
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
  loop: "{{ bootstrap_users|default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install git repos per user
  git:
    repo: "{{ item[1].src }}"
    dest: "{{ item[1].dest }}"
    depth: 1
    accept_hostkey: yes
    version: "{{ item[1].version }}"
  become_user: "{{ item[0].name }}"
  become: yes
  loop: "{{ bootstrap_users|default([])|subelements('repos') }}"
  loop_control:
    label: "{{ item[1].src }}"

- name: Set correct ownership for personal git repos
  file:
    name: "{{ item[1].dest }}"
    owner: "{{ item[0].name }}"
    group: "{{ item[0].name }}"
    recurse: yes
  loop: "{{ bootstrap_users|default([])|subelements('repos') }}"
  loop_control:
    label: "{{ item[1].dest }}"

- name: Execute installers for users
  command: "{{ item[1].command }}"
  become: yes
  become_user: "{{ item[0].name }}"
  loop: "{{ bootstrap_users|default([])|subelements('installers') }}"
  loop_control:
    label: "{{ item[1].command }}"
