---
# handlers file for bootstrap
- name: Restart sshd
  service:
    name: ssh
    state: restarted

- name: Reload ufw
  ufw:
    state: reloaded
  ignore_errors: yes

- name: Reload grub config
  command: update-grub 2>/dev/null
